PLJ-964 welcome open files
fonsp/Pluto.jl pull request #1015
Opened 2021-03-21 22:25 UTC by pankgeorg

Addresses #964, giving the ability to paste/move .jl files into the welcome screen.

Starts at `### A Pluto.jl notebook`, counts # of cells and searches for  `# ╔═╡ Cell order:` to get the end.

Used @ctrekker 's idea for uploading the notebook. That comes with a small fix on Webserver.jl which I don't really get tbh.

Feedback welcome!!

2021-03-23 22:48 UTC, ctrekker approved these changes
Everything works great for me! I do get warnings from Pluto about requests having a body (from WebServer.jl:226), but looking at the code it doesn't seem to take any action based on that warning.

2021-03-23 22:50 UTC, ctrekker commented
I'm not sure if this would belong in this PR, but would it be possible to convert non-Pluto notebooks (aka normal jl files) into Pluto notebooks if they were pasted in?

2021-03-24 07:53 UTC, pankgeorg commented
> I don't think this feature would belong in this PR, but would it be possible to convert non-Pluto notebooks (aka normal jl files) into Pluto notebooks if they were pasted in?

good idea. I'm going to remove the notebook detection for **files** so we can add the conversion step [here](https://github.com/fonsp/Pluto.jl/pull/1015/files#diff-3c333e3778a4ca5af4d9b09f894b66615ca0ec744d1ad8726ce071bff4c07d7eR211)

2021-03-24 13:45 UTC, fonsp commented
> warnings from Pluto about requests having a body

Just delete the warning, it's left over code that doesn't make sense anymore

2021-04-22 11:20 UTC, pankgeorg commented on frontend/components/PasteHandler.js
> +        alert("Notebook not found 😥😥")
don't alert ??

2021-04-22 11:20 UTC, pankgeorg commented
### TODO

1. Make sure only valid notebooks can be pasted
2. Make sure you can paste a file into whitespace
3. Make sure open file box paste handler still works 
4. merge

2021-04-25 11:42 UTC, pankgeorg commented
Supports:
- **File drop**
- **Move text** into Pluto welcome screen
- **Paste text** into Pluto welcome screen

Ready to merge!

2021-04-26 10:25 UTC, fonsp requested changes

2021-04-26 10:25 UTC, fonsp commented on src/webserver/Static.jl
> +            return error_response(400, "Bad query", "Please <a href='https://github.com/fonsp/Pluto.jl/issues'>report this error</a>!", sprint(showerror, e, stacktrace(catch_backtrace())))
Can this endpoint open the notebook and return a `notebook_response`?

2021-04-26 10:25 UTC, fonsp commented on src/webserver/Static.jl
> +            return error_response(400, "Bad query", "Please <a href='https://github.com/fonsp/Pluto.jl/issues'>report this error</a>!", sprint(showerror, e, stacktrace(catch_backtrace())))
Something like:
```julia
try_launch_notebook_response(SessionActions.open, path, as_redirect=false, as_sample=false, title="Failed to load notebook", advice="Make sure that you copy the entire notebook file. Please <a href='https://github.com/fonsp/Pluto.jl/issues'>report this error</a>!")
```

2021-04-26 10:28 UTC, fonsp commented on frontend/components/PasteHandler.js
> +    const reply = await fetch("/notebookupload", {
This should be `./notebookupload`: all our URLs are relative, to allow Pluto to run on an nginx proxy like:
```
https://jalksfjd.binder.org/proxy/pluto/1234/index.html
```

2021-04-26 10:30 UTC, fonsp commented on frontend/components/PasteHandler.js
> +        to = text.indexOf("\n", to + 1) + 1
Can this be a `for` loop? I spent some time figuring out whether this could get stuck in an infinite loop until I realised that it's just a for loop

2021-04-26 10:33 UTC, fonsp commented on frontend/components/PasteHandler.js
> +    const text = `${inputtext}\n`
Add `.replace("\r\n","\n")`

2021-04-27 15:09 UTC, merged