Add case for handling splat assignments.
fonsp/Pluto.jl pull request #2365
Opened 2022-11-11 19:30 UTC by kcin96

This PR attempts to fix Issue #2314 by adding a case for handling splat assignments.

2022-11-11 19:46 UTC, rikhuijzer requested changes
Can a test be added to avoid future problems?

2022-11-11 20:44 UTC, kcin96 commented
Yes I can add a test.

2022-11-12 17:25 UTC, kcin96 commented
Besides adding this test under test/ExpressionExplorer.jl

```julia
  @testset "Multiple assignments" begin
        #other tests ...
        @test testee(quote
            a, b... = 0:5
        end, [],[:a, :b], [[:(:)]], [])

  end
```

are there any other tests that you can think of that can be helpful? e.g. test for y... value assignment?

2022-11-13 08:56 UTC, Pangoraw commented
Thanks for tackling this one!
You can also test the case where this pattern is used as a function argument:
```julia
f((a,b...)) = b # only defines f, no reference to a or b
```

2022-11-14 08:17 UTC, Pangoraw commented
Thanks!! :confetti_ball: 

I added an extra test with destructuring an argument:
https://github.com/fonsp/Pluto.jl/blob/54ff21d960905faa3714aad461a070066b457aa8/test/ExpressionExplorer.jl#L319-L321

2022-11-14 08:17 UTC, merged